#!/bin/bash

# 设置环境变量
export PTO_TILE_LIB_CODE_PATH=/mnt/workspace/gitCode/GBowen666/pto-isa

# 切换到项目根目录
#cd /mnt/workspace/gitCode/GBowen666/pypto/

# 清理并创建构建目录
echo "=== 清理构建目录 ==="
rm -rf build
mkdir -p build
cd build

# 配置并编译项目
echo "=== 配置项目 ==="
cmake ../ -DENABLE_UTEST=ON -DENABLE_FEATURE_PYTHON_FRONT_END=OFF

echo "=== 编译项目 ==="
make -j16

# 切换到测试执行目录
cd output/bin

# 运行测试用例
echo "=== 运行测试用例 ==="
echo ""

# 定义测试用例数组
TEST_CASES=(
    # amax test cases
    "LiteNPUCodeGenAmax.test_amax_fp16_001"
    "LiteNPUCodeGenAmax.test_amax_fp16_002"
    "LiteNPUCodeGenAmax.test_amax_fp16_003"
    "LiteNPUCodeGenAmax.test_amax_fp16_004"
    "LiteNPUCodeGenAmax.test_amax_fp16_005"
    "LiteNPUCodeGenAmax.test_amax_fp16_006"
    "LiteNPUCodeGenAmax.test_amax_fp16_007"
    "LiteNPUCodeGenAmax.test_amax_fp16_008"
    "LiteNPUCodeGenAmax.test_amax_fp16_009"
    "LiteNPUCodeGenAmax.test_amax_fp16_010"
    "LiteNPUCodeGenAmax.test_amax_fp16_011"
    "LiteNPUCodeGenAmax.test_amax_fp16_012"
    "LiteNPUCodeGenAmax.test_amax_fp16_013"
    "LiteNPUCodeGenAmax.test_amax_fp16_014"
    "LiteNPUCodeGenAmax.test_amax_fp16_015"
    "LiteNPUCodeGenAmax.test_amax_fp32_001"
    "LiteNPUCodeGenAmax.test_amax_fp32_002"
    "LiteNPUCodeGenAmax.test_amax_fp32_003"
    "LiteNPUCodeGenAmax.test_amax_fp32_004"
    "LiteNPUCodeGenAmax.test_amax_fp32_005"
    "LiteNPUCodeGenAmax.test_amax_fp32_006"
    "LiteNPUCodeGenAmax.test_amax_fp32_007"
    "LiteNPUCodeGenAmax.test_amax_fp32_008"
    "LiteNPUCodeGenAmax.test_amax_fp32_009"
    "LiteNPUCodeGenAmax.test_amax_fp32_010"
    "LiteNPUCodeGenAmax.test_amax_fp32_011"
    "LiteNPUCodeGenAmax.test_amax_fp32_012"
    "LiteNPUCodeGenAmax.test_amax_fp32_013"
    "LiteNPUCodeGenAmax.test_amax_fp32_014"
    "LiteNPUCodeGenAmax.test_amax_fp32_015"
    # fp16 test cases
    "LiteNPUCodeGenAmax.test_amax_fp16_001"
    "LiteNPUCodeGenAmax.test_amax_fp16_002"
    "LiteNPUCodeGenAmax.test_amax_fp16_003"
    "LiteNPUCodeGenAmax.test_amax_fp16_004"
    "LiteNPUCodeGenAmax.test_amax_fp16_005"
    "LiteNPUCodeGenAmax.test_amax_fp16_006"
    "LiteNPUCodeGenAmax.test_amax_fp16_007"
    "LiteNPUCodeGenAmax.test_amax_fp16_008"
    "LiteNPUCodeGenAmax.test_amax_fp16_009"
    "LiteNPUCodeGenAmax.test_amax_fp16_010"
    "LiteNPUCodeGenAmax.test_amax_fp16_011"
    "LiteNPUCodeGenAmax.test_amax_fp16_012"
    "LiteNPUCodeGenAmax.test_amax_fp16_013"
    "LiteNPUCodeGenAmax.test_amax_fp16_014"
    "LiteNPUCodeGenAmax.test_amax_fp16_015"
    
    # amin test cases
    "LiteNPUCodeGenAmin.test_amin_fp16_001"
    "LiteNPUCodeGenAmin.test_amin_fp16_002"
    "LiteNPUCodeGenAmin.test_amin_fp16_003"
    "LiteNPUCodeGenAmin.test_amin_fp16_004"
    "LiteNPUCodeGenAmin.test_amin_fp16_005"
    "LiteNPUCodeGenAmin.test_amin_fp16_006"
    "LiteNPUCodeGenAmin.test_amin_fp16_007"
    "LiteNPUCodeGenAmin.test_amin_fp16_008"
    "LiteNPUCodeGenAmin.test_amin_fp16_009"
    "LiteNPUCodeGenAmin.test_amin_fp16_010"
    "LiteNPUCodeGenAmin.test_amin_fp16_011"
    "LiteNPUCodeGenAmin.test_amin_fp16_012"
    "LiteNPUCodeGenAmin.test_amin_fp16_013"
    "LiteNPUCodeGenAmin.test_amin_fp16_014"
    "LiteNPUCodeGenAmin.test_amin_fp16_015"
    "LiteNPUCodeGenAmin.test_amin_fp32_001"
    "LiteNPUCodeGenAmin.test_amin_fp32_002"
    "LiteNPUCodeGenAmin.test_amin_fp32_003"
    "LiteNPUCodeGenAmin.test_amin_fp32_004"
    "LiteNPUCodeGenAmin.test_amin_fp32_005"
    "LiteNPUCodeGenAmin.test_amin_fp32_006"
    "LiteNPUCodeGenAmin.test_amin_fp32_007"
    "LiteNPUCodeGenAmin.test_amin_fp32_008"
    "LiteNPUCodeGenAmin.test_amin_fp32_009"
    "LiteNPUCodeGenAmin.test_amin_fp32_010"
    "LiteNPUCodeGenAmin.test_amin_fp32_011"
    "LiteNPUCodeGenAmin.test_amin_fp32_012"
    "LiteNPUCodeGenAmin.test_amin_fp32_013"
    "LiteNPUCodeGenAmin.test_amin_fp32_014"
    "LiteNPUCodeGenAmin.test_amin_fp32_015"
    
    # sum test cases
    "LiteNPUCodeGenSum.test_sum_fp32_001"
    "LiteNPUCodeGenSum.test_sum_fp32_002"
    "LiteNPUCodeGenSum.test_sum_fp32_003"
    "LiteNPUCodeGenSum.test_sum_fp32_004"
    "LiteNPUCodeGenSum.test_sum_fp32_005"
    "LiteNPUCodeGenSum.test_sum_fp32_006"
    "LiteNPUCodeGenSum.test_sum_fp32_007"
    "LiteNPUCodeGenSum.test_sum_fp32_008"
    "LiteNPUCodeGenSum.test_sum_fp32_009"
    "LiteNPUCodeGenSum.test_sum_fp32_010"
    "LiteNPUCodeGenSum.test_sum_fp32_011"
    "LiteNPUCodeGenSum.test_sum_fp32_012"
    "LiteNPUCodeGenSum.test_sum_fp32_013"
    "LiteNPUCodeGenSum.test_sum_fp32_014"
    "LiteNPUCodeGenSum.test_sum_fp32_015"
    # fp16 test cases
    "LiteNPUCodeGenSum.test_sum_fp16_001"
    "LiteNPUCodeGenSum.test_sum_fp16_002"
    "LiteNPUCodeGenSum.test_sum_fp16_003"
    "LiteNPUCodeGenSum.test_sum_fp16_004"
    "LiteNPUCodeGenSum.test_sum_fp16_005"
    "LiteNPUCodeGenSum.test_sum_fp16_006"
    "LiteNPUCodeGenSum.test_sum_fp16_007"
    "LiteNPUCodeGenSum.test_sum_fp16_008"
    "LiteNPUCodeGenSum.test_sum_fp16_009"
    "LiteNPUCodeGenSum.test_sum_fp16_010"
    "LiteNPUCodeGenSum.test_sum_fp16_011"
    "LiteNPUCodeGenSum.test_sum_fp16_012"
    "LiteNPUCodeGenSum.test_sum_fp16_013"
    "LiteNPUCodeGenSum.test_sum_fp16_014"
    "LiteNPUCodeGenSum.test_sum_fp16_015"
    # int32 test cases
    "LiteNPUCodeGenSum.test_sum_int32_001"
    "LiteNPUCodeGenSum.test_sum_int32_002"
    "LiteNPUCodeGenSum.test_sum_int32_003"
    "LiteNPUCodeGenSum.test_sum_int32_004"
    "LiteNPUCodeGenSum.test_sum_int32_005"
    "LiteNPUCodeGenSum.test_sum_int32_006"
    "LiteNPUCodeGenSum.test_sum_int32_007"
    "LiteNPUCodeGenSum.test_sum_int32_008"
    "LiteNPUCodeGenSum.test_sum_int32_009"
    "LiteNPUCodeGenSum.test_sum_int32_010"
    "LiteNPUCodeGenSum.test_sum_int32_011"
    "LiteNPUCodeGenSum.test_sum_int32_012"
    "LiteNPUCodeGenSum.test_sum_int32_013"
    "LiteNPUCodeGenSum.test_sum_int32_014"
    "LiteNPUCodeGenSum.test_sum_int32_015"
    
    # transpose test cases
    "LiteNPUCodeGenTranspose.test_transpose_fp16_001"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_002"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_003"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_004"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_005"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_006"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_007"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_008"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_009"
    "LiteNPUCodeGenTranspose.test_transpose_fp16_010"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_001"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_002"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_003"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_004"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_005"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_006"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_007"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_008"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_009"
    "LiteNPUCodeGenTranspose.test_transpose_fp32_010"
    "LiteNPUCodeGenTranspose.test_transpose_int32_001"
    "LiteNPUCodeGenTranspose.test_transpose_int32_002"
    "LiteNPUCodeGenTranspose.test_transpose_int32_003"
    "LiteNPUCodeGenTranspose.test_transpose_int32_004"
    "LiteNPUCodeGenTranspose.test_transpose_int32_005"
    "LiteNPUCodeGenTranspose.test_transpose_int16_001"
    "LiteNPUCodeGenTranspose.test_transpose_int16_002"
    "LiteNPUCodeGenTranspose.test_transpose_int16_003"
    "LiteNPUCodeGenTranspose.test_transpose_int16_004"
    "LiteNPUCodeGenTranspose.test_transpose_int16_005"
    "LiteNPUCodeGenTranspose.test_transpose_int16_006"
    "LiteNPUCodeGenTranspose.test_transpose_int16_007"
    "LiteNPUCodeGenTranspose.test_transpose_int16_008"
    "LiteNPUCodeGenTranspose.test_transpose_int16_009"
    "LiteNPUCodeGenTranspose.test_transpose_int16_010"
    
    # reshape test cases
    "LiteNPUCodeGenReshape.test_reshape_fp16_001"
    "LiteNPUCodeGenReshape.test_reshape_fp16_002"
    "LiteNPUCodeGenReshape.test_reshape_fp16_003"
    "LiteNPUCodeGenReshape.test_reshape_fp16_004"
    "LiteNPUCodeGenReshape.test_reshape_fp16_005"
    "LiteNPUCodeGenReshape.test_reshape_fp16_006"
    "LiteNPUCodeGenReshape.test_reshape_fp16_007"
    "LiteNPUCodeGenReshape.test_reshape_fp16_008"
    "LiteNPUCodeGenReshape.test_reshape_fp16_009"
    "LiteNPUCodeGenReshape.test_reshape_fp16_010"
    "LiteNPUCodeGenReshape.test_reshape_fp32_001"
    "LiteNPUCodeGenReshape.test_reshape_fp32_002"
    "LiteNPUCodeGenReshape.test_reshape_fp32_003"
    "LiteNPUCodeGenReshape.test_reshape_fp32_004"
    "LiteNPUCodeGenReshape.test_reshape_fp32_005"
    "LiteNPUCodeGenReshape.test_reshape_fp32_006"
    "LiteNPUCodeGenReshape.test_reshape_fp32_007"
    "LiteNPUCodeGenReshape.test_reshape_fp32_008"
    "LiteNPUCodeGenReshape.test_reshape_fp32_009"
    "LiteNPUCodeGenReshape.test_reshape_fp32_010"
    "LiteNPUCodeGenReshape.test_reshape_inplace_fp32_001"
    "LiteNPUCodeGenReshape.test_reshape_inplace_fp32_002"
    "LiteNPUCodeGenReshape.test_reshape_inplace_fp32_003"
    "LiteNPUCodeGenReshape.test_reshape_inplace_fp32_004"
    "LiteNPUCodeGenReshape.test_reshape_inplace_fp32_005"
    "LiteNPUCodeGenReshape.test_reshape_int8_001"
    "LiteNPUCodeGenReshape.test_reshape_int8_002"
    "LiteNPUCodeGenReshape.test_reshape_int8_003"
    "LiteNPUCodeGenReshape.test_reshape_int8_004"
    "LiteNPUCodeGenReshape.test_reshape_int8_005"
    "LiteNPUCodeGenReshape.test_reshape_int16_001"
    "LiteNPUCodeGenReshape.test_reshape_int16_002"
    "LiteNPUCodeGenReshape.test_reshape_int16_003"
    "LiteNPUCodeGenReshape.test_reshape_int16_004"
    "LiteNPUCodeGenReshape.test_reshape_int16_005"
    "LiteNPUCodeGenReshape.test_reshape_int32_001"
    "LiteNPUCodeGenReshape.test_reshape_int32_002"
    "LiteNPUCodeGenReshape.test_reshape_int32_003"
    "LiteNPUCodeGenReshape.test_reshape_int32_004"
    "LiteNPUCodeGenReshape.test_reshape_int32_005"
    
    # unsqueeze test cases
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_001"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_002"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_003"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_004"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_005"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_006"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_007"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_008"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_009"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp16_010"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_001"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_002"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_003"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_004"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_005"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_006"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_007"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_008"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_009"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_fp32_010"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int32_001"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int32_002"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int32_003"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int32_004"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int32_005"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int8_001"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int8_002"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int8_003"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int8_004"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int8_005"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int16_001"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int16_002"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int16_003"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int16_004"
    "LiteNPUCodeGenUnsqueeze.test_unsqueeze_int16_005"
    
    # view test cases
    "LiteNPUCodeGenView.test_view_fp16_001"
    "LiteNPUCodeGenView.test_view_fp16_002"
    "LiteNPUCodeGenView.test_view_fp16_003"
    "LiteNPUCodeGenView.test_view_fp16_004"
    "LiteNPUCodeGenView.test_view_fp16_005"
    "LiteNPUCodeGenView.test_view_fp16_006"
    "LiteNPUCodeGenView.test_view_fp16_007"
    "LiteNPUCodeGenView.test_view_fp16_008"
    "LiteNPUCodeGenView.test_view_fp16_009"
    "LiteNPUCodeGenView.test_view_fp16_010"
    "LiteNPUCodeGenView.test_view_fp32_001"
    "LiteNPUCodeGenView.test_view_fp32_002"
    "LiteNPUCodeGenView.test_view_fp32_003"
    "LiteNPUCodeGenView.test_view_fp32_004"
    "LiteNPUCodeGenView.test_view_fp32_005"
    "LiteNPUCodeGenView.test_view_fp32_006"
    "LiteNPUCodeGenView.test_view_fp32_007"
    "LiteNPUCodeGenView.test_view_fp32_008"
    "LiteNPUCodeGenView.test_view_fp32_009"
    "LiteNPUCodeGenView.test_view_fp32_010"
    "LiteNPUCodeGenView.test_view_dtype_fp32_001"
    "LiteNPUCodeGenView.test_view_dtype_fp32_002"
    "LiteNPUCodeGenView.test_view_dtype_fp32_003"
    "LiteNPUCodeGenView.test_view_dtype_fp32_004"
    "LiteNPUCodeGenView.test_view_dtype_fp32_005"
    "LiteNPUCodeGenView.test_view_int8_001"
    "LiteNPUCodeGenView.test_view_int8_002"
    "LiteNPUCodeGenView.test_view_int8_003"
    "LiteNPUCodeGenView.test_view_int16_001"
    "LiteNPUCodeGenView.test_view_int16_002"
    "LiteNPUCodeGenView.test_view_int16_003"
    "LiteNPUCodeGenView.test_view_int32_001"
    "LiteNPUCodeGenView.test_view_int32_002"
    "LiteNPUCodeGenView.test_view_int32_003"
    
    # assemble test cases
    "LiteNPUCodeGenAssemble.test_assemble_fp16_001"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_002"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_003"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_004"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_005"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_006"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_007"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_008"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_009"
    "LiteNPUCodeGenAssemble.test_assemble_fp16_010"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_001"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_002"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_003"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_004"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_005"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_006"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_007"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_008"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_009"
    "LiteNPUCodeGenAssemble.test_assemble_fp32_010"
    "LiteNPUCodeGenAssemble.test_assemble_int8_001"
    "LiteNPUCodeGenAssemble.test_assemble_int8_002"
    "LiteNPUCodeGenAssemble.test_assemble_int8_003"
    "LiteNPUCodeGenAssemble.test_assemble_int8_004"
    "LiteNPUCodeGenAssemble.test_assemble_int8_005"
    "LiteNPUCodeGenAssemble.test_assemble_int16_001"
    "LiteNPUCodeGenAssemble.test_assemble_int16_002"
    "LiteNPUCodeGenAssemble.test_assemble_int16_003"
    "LiteNPUCodeGenAssemble.test_assemble_int16_004"
    "LiteNPUCodeGenAssemble.test_assemble_int16_005"
    "LiteNPUCodeGenAssemble.test_assemble_int32_001"
    "LiteNPUCodeGenAssemble.test_assemble_int32_002"
    "LiteNPUCodeGenAssemble.test_assemble_int32_003"
    "LiteNPUCodeGenAssemble.test_assemble_int32_004"
    "LiteNPUCodeGenAssemble.test_assemble_int32_005"
    "LiteNPUCodeGenAssemble.test_assemble_list_fp32_001"
    "LiteNPUCodeGenAssemble.test_assemble_list_fp32_002"
    "LiteNPUCodeGenAssemble.test_assemble_list_fp32_003"
    "LiteNPUCodeGenAssemble.test_assemble_list_multi_shape_001"
    "LiteNPUCodeGenAssemble.test_assemble_list_multi_shape_002"
)

# 初始化统计变量
total_tests=${#TEST_CASES[@]}
passed_tests=0
failed_tests=0
failed_cases=()

# 运行所有测试用例
for test_case in "${TEST_CASES[@]}"; do
    echo "运行测试: $test_case"
    ./tile_fwk_utest --gtest_filter="$test_case"
    
    if [ $? -eq 0 ]; then
        echo "✅ 通过: $test_case"
        ((passed_tests++))
    else
        echo "❌ 失败: $test_case"
        ((failed_tests++))
        failed_cases+=("$test_case")
    fi
    echo ""
done

# 输出测试结果统计
echo "=== 测试结果统计 ==="
echo "总测试用例数: $total_tests"
echo "通过测试用例数: $passed_tests"
echo "失败测试用例数: $failed_tests"

if [ $failed_tests -gt 0 ]; then
    echo ""
    echo "失败的测试用例:"
    for failed_case in "${failed_cases[@]}"; do
        echo "  - $failed_case"
    done
    exit 1
else
    echo ""
    echo "🎉 所有测试用例通过！"
    exit 0
fi