#!/bin/bash
#
# 将 pmu_user_access.ko 二进制转换为 C++ 头文件，嵌入到 device 代码中
#
# 用法: ./embed_ko_to_code.sh pmu_user_access.ko output.h
#

set -e

KO_FILE="${1:-pmu_user_access.ko}"
OUTPUT_FILE="${2:-pmu_user_access_ko_embedded.h}"

if [ ! -f "$KO_FILE" ]; then
    echo "Error: Kernel module file '$KO_FILE' not found"
    exit 1
fi

echo "Embedding $KO_FILE into $OUTPUT_FILE..."

cat > "$OUTPUT_FILE" << EOF
/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \\file $(basename "$OUTPUT_FILE")
 * \\brief Embedded pmu_user_access.ko image.
 *
 * Generated from $(basename "$KO_FILE") by tools/scripts/pmu_user_access/embed_ko_to_code.sh.
 * Do not edit this file manually.
 */

#pragma once

#ifdef __DEVICE__

#include <cstddef>
#include <cstdint>

#define PMU_USER_ACCESS_KO_EMBEDDED 1

namespace npu::tile_fwk {

EOF

# xxd -i 生成的数组名取决于文件名，这里统一转换成命名空间内的 inline constexpr 变量。
xxd -i "$KO_FILE" | awk '
    /^unsigned char / {
        print "alignas(16) static const unsigned char kEmbeddedPmuUserAccessKo[] = {";
        next;
    }
    /^unsigned int .*_len = / {
        next;
    }
    {
        print;
    }
' >> "$OUTPUT_FILE"

cat >> "$OUTPUT_FILE" << 'EOF'

inline const unsigned char* GetEmbeddedPmuKoData()
{
    return kEmbeddedPmuUserAccessKo;
}

inline size_t GetEmbeddedPmuKoLen()
{
    return sizeof(kEmbeddedPmuUserAccessKo);
}

} // namespace npu::tile_fwk

#endif // __DEVICE__
EOF

echo "Done! Generated $OUTPUT_FILE ($(wc -c < "$KO_FILE") bytes embedded)"
echo ""
echo "Usage example:"
echo "  #include \"pmu_user_access_ko_embedded.h\""
echo "  #include \"pmu_ko_loader.h\""
echo ""
echo "  npu::tile_fwk::PmuInitEmbeddedKo();"