/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

/**
 * @file backend_910b_cce_manual_ops.cpp
 * @brief CCE backend op registration for manual (non-SSA) operations.
 *
 * Manual ops carry an explicit pre-allocated output tile as their last argument.
 * Convention: args = [input0, input1, ..., output_tile]
 * The helpers here extract output from args.back() instead of GetCurrentResultTarget().
 */

#include <cstddef>
#include <cstdint>
#include <memory>
#include <sstream>
#include <string>
#include <utility>

#include "block/backend/910B_CCE/backend_910b_cce.h"
#include "block/backend/common/backend.h"
#include "block/codegen/cce/cce_codegen.h"
#include "block/codegen/codegen_base.h"
#include "core/error.h"
#include "core/logging.h"
#include "ir/expr.h"
#include "ir/kind_traits.h"
#include "ir/memref.h"
#include "ir/pipe.h"
#include "ir/type.h"

namespace pypto {
namespace backend {
using ir::DataType;

// ============================================================================
// Helper: Produce a type string for use in TMOV<Type, Type, Mode> templates.
//
// For simple Var tiles, ``decltype(<name>)`` is fine and bisheng accepts it.
// For array-subscript expressions like ``arr[ctx.cursor % 2]`` (generated by
// NBuffer auto-rotate), bisheng does not accept ``decltype(arr[idx])`` — so
// we resolve the tile's concrete C++ Tile<...> type from its IR TileType
// instead, matching the declaration emitted in the prologue.
// ============================================================================
static std::string TileTypeStringForTemplate(codegen::CCECodegen& codegen,
                                             const std::string& expr,
                                             const ir::ExprPtr& arg) {
  if (expr.find('[') == std::string::npos) {
    return "decltype(" + expr + ")";
  }
  if (arg) {
    if (auto tile_type = ir::As<ir::TileType>(arg->GetType())) {
      int64_t rows = 1;
      int64_t cols = 1;
      if (tile_type->shape_.size() >= 1) {
        if (auto ci = ir::As<ir::ConstInt>(tile_type->shape_[0])) rows = ci->value_;
      }
      if (tile_type->shape_.size() >= 2) {
        if (auto ci = ir::As<ir::ConstInt>(tile_type->shape_[1])) cols = ci->value_;
      }
      return codegen.GetTypeConverter().ConvertTileType(tile_type, rows, cols);
    }
  }
  // Fallback: still use decltype; may still fail but better than nothing.
  return "decltype(" + expr + ")";
}

// ============================================================================
// Helper: Manual binary op — args = [lhs, rhs, dst]
// Emits: OP(dst, lhs, rhs);
// ============================================================================
static std::string MakeManualBinaryCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                               codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << ": expected 3 args (lhs, rhs, dst), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + lhs + ", " + rhs + ");");
  return "";
}

// ============================================================================
// Helper: Manual unary op �?args = [src, dst]
// Emits: OP(dst, src);
// ============================================================================
static std::string MakeManualUnaryCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                              codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << cce_op_name << ": expected 2 args (src, dst), got " << op->args_.size();
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + src + ");");
  return "";
}

// ============================================================================
// Helper: Manual scalar op �?args = [tile, scalar, dst]
// Emits: OP(dst, tile, scalar);
// ============================================================================
static std::string MakeManualScalarCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                               codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << ": expected 3 args (tile, scalar, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  std::string scalar = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + tile + ", " + scalar + ");");
  return "";
}

// ============================================================================
// Helper: Manual reduction op �?args = [tile, tmp, dst]
// Emits: OP(dst, tile, tmp);
// ============================================================================
static std::string MakeManualRowReductionCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                     codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << ": expected 3 args (tile, tmp, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  std::string tmp = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + tile + ", " + tmp + ");");
  return "";
}

// ============================================================================
// Helper: Manual col-reduction op �?args = [tile, tmp, dst]
// TCOLMAX emits: TCOLMAX(dst, tile);          �?2-arg form (no tmp)
// TCOLSUM emits: TCOLSUM(dst, tile, tmp, false); �?4-arg form
// ============================================================================
static std::string MakeManualColMaxCodegenCCE(const ir::CallPtr& op,
                                              codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "TCOLMAX: expected 3 args (tile, tmp, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  // args_[1] is tmp �?not used by TCOLMAX
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TCOLMAX(" + dst + ", " + tile + ");");
  return "";
}

static std::string MakeManualColSumCodegenCCE(const ir::CallPtr& op,
                                              codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "TCOLSUM: expected 3 args (tile, tmp, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  std::string tmp = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TCOLSUM(" + dst + ", " + tile + ", " + tmp + ", false);");
  return "";
}

// ============================================================================
// Helper: Manual row-expand op �?args = [tile, reduction_tile, dst]
// Emits: OP(dst, tile, reduction_tile);
// ============================================================================
static std::string MakeManualRowExpandCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                  codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << ": expected 3 args (tile, red, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  std::string red = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + tile + ", " + red + ");");
  return "";
}

// Helper function to compute stride-based offset
// In single-file mode: compute strides from IR tensor shape (no Tensor struct available)
// In normal mode: use Tensor struct strides (same as backend_910b_cce_ops.cpp)
static std::string ComputeManualOffset(codegen::CCECodegen& codegen, const std::string& tensor_var_name,
                                       const ir::MakeTuplePtr& offsets,
                                       const ir::TensorTypePtr& tensor_type) {
  if (codegen.IsSingleFileMode()) {
    return codegen.ComputeIRBasedOffset(tensor_type, offsets);
  }
  // Normal mode: use Tensor struct strides
  std::string tensor_struct = codegen.GetTensorStruct(tensor_var_name);
  std::ostringstream offset_computation;
  offset_computation << "(" << tensor_struct << "->start_offset";
  for (size_t i = 0; i < offsets->elements_.size(); ++i) {
    offset_computation << " + " << codegen.GetExprAsCode(offsets->elements_[i]) << " * " << tensor_struct
                       << "->strides[" << i << "]";
  }
  offset_computation << ")";
  return offset_computation.str();
}

static bool IsNZTensorType(const ir::TensorTypePtr& tensor_type) {
  return tensor_type && tensor_type->tensor_view_.has_value() &&
         tensor_type->tensor_view_->layout == ir::TensorLayout::NZ;
}

static int64_t GetNZInnerCols(const DataType& dtype) {
  if (dtype == DataType::BOOL || dtype == DataType::INT8 || dtype == DataType::UINT8) {
    return 32;
  }
  if (dtype == DataType::FP16 || dtype == DataType::BF16 ||
      dtype == DataType::INT16 || dtype == DataType::UINT16) {
    return 16;
  }
  if (dtype == DataType::FP32 || dtype == DataType::INT32 || dtype == DataType::UINT32) {
    return 8;
  }
  if (dtype == DataType::INT64 || dtype == DataType::UINT64) {
    return 4;
  }
  throw pypto::ir::ValueError("CCE NZ store does not support destination dtype " + dtype.ToString());
}

static int64_t GetStaticConstIntOrThrow(const ir::ExprPtr& expr, const std::string& message) {
  auto value = ir::As<ir::ConstInt>(expr);
  if (!value) {
    throw pypto::ir::ValueError(message);
  }
  return value->value_;
}

static bool IsConstZero(const ir::ExprPtr& expr) {
  auto value = ir::As<ir::ConstInt>(expr);
  return value && value->value_ == 0;
}

static void ValidateCCEStoreNZPreconditions(const std::string& op_name,
                                            const ir::ExprPtr& src_expr,
                                            const ir::MakeTuplePtr& offsets,
                                            const ir::TensorTypePtr& dst_tensor_type) {
  if (!IsNZTensorType(dst_tensor_type)) {
    return;
  }

  auto src_tile_type = ir::As<ir::TileType>(src_expr->GetType());
  CHECK(src_tile_type != nullptr) << op_name << ": source must be TileType";
  CHECK(src_tile_type->memref_.has_value()) << op_name << ": source tile must have an allocated memory space";
  if (src_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Acc) {
    throw pypto::ir::ValueError(op_name + ": CCE NZ output currently only supports Acc source tiles");
  }

  if (dst_tensor_type->shape_.size() != 2) {
    throw pypto::ir::ValueError(op_name + ": CCE NZ output currently requires a 2D destination tensor");
  }
  if (offsets->elements_.size() != 2 || !IsConstZero(offsets->elements_[0]) || !IsConstZero(offsets->elements_[1])) {
    throw pypto::ir::ValueError(op_name + ": CCE NZ output currently requires offsets=[0, 0]");
  }

  const int64_t rows = GetStaticConstIntOrThrow(
      dst_tensor_type->shape_[0], op_name + ": CCE NZ output currently requires a static destination row shape");
  const int64_t cols = GetStaticConstIntOrThrow(
      dst_tensor_type->shape_[1], op_name + ": CCE NZ output currently requires a static destination column shape");
  const int64_t c0 = GetNZInnerCols(dst_tensor_type->dtype_);
  if (rows % 16 != 0 || cols % c0 != 0) {
    throw pypto::ir::ValueError(
        op_name + ": CCE NZ output requires rows divisible by 16 and cols divisible by the destination C0 size");
  }
}

// ============================================================================
// manual.load �?args = [tensor, offsets, out_tile]
// Emits: TASSIGN(tensor_global, ptr + offset); TLOAD(out_tile, tensor_global);
// ============================================================================
static std::string MakeManualLoadCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.load requires 3 arguments: tensor, offsets, out_tile";

  auto src_tensor_var_ptr = std::dynamic_pointer_cast<const ir::Var>(op->args_[0]);
  CHECK(src_tensor_var_ptr != nullptr) << "manual.load source tensor must be a Var";

  auto offsets_tuple = std::dynamic_pointer_cast<const ir::MakeTuple>(op->args_[1]);
  CHECK(offsets_tuple != nullptr) << "manual.load second argument must be a tuple (offsets)";

  auto out_tile = std::dynamic_pointer_cast<const ir::Var>(op->args_[2]);
  if (!out_tile) {
    // Support TupleGetItemExpr (e.g., qk_vec_buf[0]) �?resolved by GetExprAsCode below
    CHECK(ir::As<ir::TileType>(op->args_[2]->GetType()) != nullptr)
        << "manual.load third argument (out) must be a tile (Var or TupleGetItemExpr)";
  }

  std::string src_tensor_var = codegen.GetVarName(src_tensor_var_ptr);
  auto src_tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(src_tensor_var_ptr->GetType());
  CHECK(src_tensor_type != nullptr) << "manual.load source must be TensorType";

  std::string offset = ComputeManualOffset(codegen, src_tensor_var, offsets_tuple, src_tensor_type);
  std::string src_ptr = codegen.GetPointer(src_tensor_var);
  std::string out_name = codegen.GetExprAsCode(op->args_[2]);

  codegen.Emit("TASSIGN(" + src_tensor_var + ", " + src_ptr + " + " + offset + ");");
  codegen.Emit("TLOAD(" + out_name + ", " + src_tensor_var + ");");
  return "";
}

// ============================================================================
// manual.store �?args = [tile, offsets, output_tensor]
// Emits: TASSIGN(tensor_global, ptr + offset); TSTORE(tensor_global, tile);
// ============================================================================
static std::string MakeManualStoreCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.store requires 3 arguments: tile, offsets, output_tensor";

  std::string src_tile = codegen.GetExprAsCode(op->args_[0]);

  auto offsets_tuple = std::dynamic_pointer_cast<const ir::MakeTuple>(op->args_[1]);
  CHECK(offsets_tuple != nullptr) << "manual.store second argument must be a tuple (offsets)";

  auto dst_tensor_var_ptr = std::dynamic_pointer_cast<const ir::Var>(op->args_[2]);
  CHECK(dst_tensor_var_ptr != nullptr) << "manual.store destination tensor must be a Var";

  std::string dst_tensor_var = codegen.GetVarName(dst_tensor_var_ptr);
  auto dst_tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(dst_tensor_var_ptr->GetType());
  CHECK(dst_tensor_type != nullptr) << "manual.store destination must be TensorType";
  ValidateCCEStoreNZPreconditions("manual.store", op->args_[0], offsets_tuple, dst_tensor_type);

  std::string offset = ComputeManualOffset(codegen, dst_tensor_var, offsets_tuple, dst_tensor_type);
  std::string dst_ptr = codegen.GetPointer(dst_tensor_var);

  codegen.Emit("TASSIGN(" + dst_tensor_var + ", " + dst_ptr + " + " + offset + ");");

  // Build template parameters: TSTORE<TileData, GlobalData, AtomicType, ReluPreMode>(dst, src, ...)
  // Per pto-isa: template order is <TileData, GlobalData, AtomicType, ReluPreMode>
  // Function arg order is (GlobalData& dst, TileData& src, ...)
  std::string relu_template;

  if (op->HasKwarg("relu_pre_mode")) {
    const std::string& relu_str = op->GetKwarg<std::string>("relu_pre_mode");
    std::string relu_enum;
    if (relu_str == "no_relu") {
      relu_enum = "ReluPreMode::NoRelu";
    } else if (relu_str == "normal_relu") {
      relu_enum = "ReluPreMode::NormalRelu";
    } else {
      throw pypto::ir::ValueError("Invalid relu_pre_mode: " + relu_str);
    }
    relu_template = relu_enum;
  }

  // Build function arguments
  std::string args = dst_tensor_var + ", " + src_tile;

  if (op->HasKwarg("pre_quant_scalar")) {
    int pre_quant = op->GetKwarg<int>("pre_quant_scalar");
    args += ", " + std::to_string(pre_quant);
  }

  // Emit TSTORE
  if (!relu_template.empty()) {
    // TSTORE<TileData, GlobalData, AtomicType::AtomicNone, ReluPreMode>(dst, src[, preQuant])
    std::string src_type = TileTypeStringForTemplate(codegen, src_tile, op->args_[0]);
    codegen.Emit("TSTORE<" + src_type + ", decltype(" + dst_tensor_var + "), AtomicType::AtomicNone, " + relu_template + ">(" + args + ");");
  } else if (op->HasKwarg("pre_quant_scalar")) {
    // TSTORE<TileData, GlobalData>(dst, src, preQuant) — default AtomicType & ReluPreMode
    std::string src_type = TileTypeStringForTemplate(codegen, src_tile, op->args_[0]);
    codegen.Emit("TSTORE<" + src_type + ", decltype(" + dst_tensor_var + ")>(" + args + ");");
  } else {
    codegen.Emit("TSTORE(" + args + ");");
  }
  return "";
}

// ============================================================================
// manual.store_fp �?args = [tile, fp_tile, offsets, output_tensor]
// Emits: TASSIGN(tensor_global, ptr + offset); TSTORE_FP(tensor_global, tile, fp_tile);
// ============================================================================
static std::string MakeManualStoreFpCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 4)
      << "manual.store_fp requires 4 arguments: tile, fp_tile, offsets, output_tensor";

  auto src_tile_type = ir::As<ir::TileType>(op->args_[0]->GetType());
  CHECK(src_tile_type != nullptr) << "manual.store_fp source must be TileType";
  CHECK(src_tile_type->memref_.has_value())
      << "manual.store_fp source tile must have an allocated memory space";
  if (src_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Acc) {
    throw pypto::ir::ValueError("manual.store_fp: source tile must be allocated in Acc memory");
  }

  auto fp_tile_type = ir::As<ir::TileType>(op->args_[1]->GetType());
  CHECK(fp_tile_type != nullptr) << "manual.store_fp fp tile must be TileType";
  CHECK(fp_tile_type->memref_.has_value())
      << "manual.store_fp fp tile must have an allocated memory space";
  if (fp_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Scaling) {
    throw pypto::ir::ValueError("manual.store_fp: fp tile must be allocated in Scaling memory");
  }

  auto offsets_tuple = std::dynamic_pointer_cast<const ir::MakeTuple>(op->args_[2]);
  CHECK(offsets_tuple != nullptr) << "manual.store_fp third argument must be a tuple (offsets)";

  auto dst_tensor_var_ptr = std::dynamic_pointer_cast<const ir::Var>(op->args_[3]);
  CHECK(dst_tensor_var_ptr != nullptr) << "manual.store_fp destination tensor must be a Var";

  std::string dst_tensor_var = codegen.GetVarName(dst_tensor_var_ptr);
  auto dst_tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(dst_tensor_var_ptr->GetType());
  CHECK(dst_tensor_type != nullptr) << "manual.store_fp destination must be TensorType";
  ValidateCCEStoreNZPreconditions("manual.store_fp", op->args_[0], offsets_tuple, dst_tensor_type);

  std::string offset = ComputeManualOffset(codegen, dst_tensor_var, offsets_tuple, dst_tensor_type);
  std::string dst_ptr = codegen.GetPointer(dst_tensor_var);
  std::string src_tile = codegen.GetExprAsCode(op->args_[0]);
  std::string fp_tile = codegen.GetExprAsCode(op->args_[1]);

  codegen.Emit("TASSIGN(" + dst_tensor_var + ", " + dst_ptr + " + " + offset + ");");
  codegen.Emit("TSTORE_FP(" + dst_tensor_var + ", " + src_tile + ", " + fp_tile + ");");
  return "";
}

// ============================================================================
// manual.make_tile �?no-op (tile already declared in prologue)
// ============================================================================
static std::string MakeManualMakeTileCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  (void)op;
  (void)codegen_base;
  return "";
}

// ============================================================================
// manual.insert �?args = [src, index_row, index_col, dst] or [src, index_row, index_col, offset, dst]
// Emits TINSERT(dst, src, indexRow, indexCol);
// With offset: Emits TASSIGN(dst, base + offset); TINSERT(...); TASSIGN(dst, base);
// ============================================================================
static std::string MakeManualInsertCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 4 || op->args_.size() == 5)
      << "manual.insert: expected 4 or 5 args, got " << op->args_.size();

  bool has_offset = (op->args_.size() == 5);
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string index_row = codegen.GetExprAsCode(op->args_[1]);
  std::string index_col = codegen.GetExprAsCode(op->args_[2]);
  std::string dst, offset, base_addr;

  if (has_offset) {
    offset = codegen.GetExprAsCode(op->args_[3]);
    dst = codegen.GetExprAsCode(op->args_[4]);
    // For array-subscript dst (e.g. NBuffer auto-rotate ``arr[ctx.cursor%2]``),
    // tile_addresses_ does not have an entry — use the runtime ``data()``
    // method to get the actual base address. Save it to a temp because
    // TASSIGN mutates ``dst.data()``; the second TASSIGN (restore) needs
    // the original address.
    if (dst.find('[') != std::string::npos) {
      static int insert_addr_counter = 0;
      std::string addr_tmp = "_tinsert_addr_" + std::to_string(insert_addr_counter++);
      codegen.Emit("uint64_t " + addr_tmp + " = (uint64_t)(" + dst + ".data());");
      base_addr = addr_tmp;
    } else {
      base_addr = codegen.GetTileAddress(dst);
    }
    codegen.Emit("TASSIGN(" + dst + ", " + base_addr + " + " + offset + ");");
  } else {
    dst = codegen.GetExprAsCode(op->args_[3]);
  }

  codegen.Emit("TINSERT(" + dst + ", " + src + ", " + index_row + ", " + index_col + ");");

  if (has_offset) {
    codegen.Emit("TASSIGN(" + dst + ", " + base_addr + ");");
  }

  return "";
}

// ============================================================================
// manual.move �?args = [src, dst]
// Emits TMOV(dst, src);
// ============================================================================
static std::string MakeManualMoveCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2)
      << "manual.move: expected 2 args, got " << op->args_.size();

  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);

  // Build template parameters
  std::string template_params = "";

  if (op->HasKwarg("acc_to_vec_mode")) {
    const std::string& mode_str = op->GetKwarg<std::string>("acc_to_vec_mode");
    std::string mode_enum;
    if (mode_str == "single_vec0") {
      mode_enum = "AccToVecMode::SingleModeVec0";
    } else if (mode_str == "single_vec1") {
      mode_enum = "AccToVecMode::SingleModeVec1";
    } else if (mode_str == "dual_split_m") {
      mode_enum = "AccToVecMode::DualModeSplitM";
    } else if (mode_str == "dual_split_n") {
      mode_enum = "AccToVecMode::DualModeSplitN";
    } else {
      throw pypto::ir::ValueError("Invalid acc_to_vec_mode: " + mode_str);
    }
    template_params = ", " + mode_enum;
  }

  if (op->HasKwarg("relu_pre_mode")) {
    const std::string& relu_str = op->GetKwarg<std::string>("relu_pre_mode");
    std::string relu_enum;
    if (relu_str == "no_relu") {
      relu_enum = "ReluPreMode::NoRelu";
    } else if (relu_str == "normal_relu") {
      relu_enum = "ReluPreMode::NormalRelu";
    } else {
      throw pypto::ir::ValueError("Invalid relu_pre_mode: " + relu_str);
    }
    template_params += ", " + relu_enum;
  }

  // Build function arguments
  std::string args = dst + ", " + src;

  if (op->HasKwarg("pre_quant_scalar")) {
    int pre_quant = op->GetKwarg<int>("pre_quant_scalar");
    args += ", " + std::to_string(pre_quant);
  }

  // Emit TMOV
  if (!template_params.empty()) {
    // decltype(arr[idx]) is not supported by bisheng — use the tile's concrete C++ Tile<...> type.
    std::string dst_type = TileTypeStringForTemplate(codegen, dst, op->args_[1]);
    std::string src_type = TileTypeStringForTemplate(codegen, src, op->args_[0]);
    codegen.Emit("TMOV<" + dst_type + ", " + src_type + template_params + ">(" + args + ");");
  } else {
    codegen.Emit("TMOV(" + args + ");");
  }

  return "";
}

// ============================================================================
// manual.move_fp �?args = [src, fp_tile, dst]
// Emits TMOV_FP(dst, src, fp) or TMOV<..., FpTileData, AccToVecMode, ReluPreMode>(dst, src, fp);
// ============================================================================
static std::string MakeManualMoveFpCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3)
      << "manual.move_fp: expected 3 args, got " << op->args_.size();

  auto src_tile_type = ir::As<ir::TileType>(op->args_[0]->GetType());
  CHECK(src_tile_type != nullptr) << "manual.move_fp source must be TileType";
  CHECK(src_tile_type->memref_.has_value())
      << "manual.move_fp source tile must have an allocated memory space";
  if (src_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Acc) {
    throw pypto::ir::ValueError("manual.move_fp: source tile must be allocated in Acc memory");
  }

  auto fp_tile_type = ir::As<ir::TileType>(op->args_[1]->GetType());
  CHECK(fp_tile_type != nullptr) << "manual.move_fp fp tile must be TileType";
  CHECK(fp_tile_type->memref_.has_value())
      << "manual.move_fp fp tile must have an allocated memory space";
  if (fp_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Scaling) {
    throw pypto::ir::ValueError("manual.move_fp: fp tile must be allocated in Scaling memory");
  }

  auto dst_tile_type = ir::As<ir::TileType>(op->args_[2]->GetType());
  CHECK(dst_tile_type != nullptr) << "manual.move_fp destination must be TileType";
  CHECK(dst_tile_type->memref_.has_value())
      << "manual.move_fp destination tile must have an allocated memory space";
  if (dst_tile_type->memref_.value()->memory_space_ != ir::MemorySpace::Vec) {
    throw pypto::ir::ValueError("manual.move_fp: destination tile must be allocated in Vec memory");
  }

  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string fp_tile = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  std::string args = dst + ", " + src + ", " + fp_tile;

  std::string relu_template;
  if (op->HasKwarg("relu_pre_mode")) {
    const std::string& relu_str = op->GetKwarg<std::string>("relu_pre_mode");
    if (relu_str == "no_relu") {
      relu_template = "ReluPreMode::NoRelu";
    } else if (relu_str == "normal_relu") {
      relu_template = "ReluPreMode::NormalRelu";
    } else {
      throw pypto::ir::ValueError("Invalid relu_pre_mode: " + relu_str);
    }
  }

  if (op->HasKwarg("acc_to_vec_mode")) {
    const std::string& mode_str = op->GetKwarg<std::string>("acc_to_vec_mode");
    std::string mode_enum;
    if (mode_str == "single_vec0") {
      mode_enum = "AccToVecMode::SingleModeVec0";
    } else if (mode_str == "single_vec1") {
      mode_enum = "AccToVecMode::SingleModeVec1";
    } else if (mode_str == "dual_split_m" || mode_str == "dual_split_n") {
      throw pypto::ir::ValueError("manual.move_fp: fp_tile only supports single-mode acc_to_vec_mode");
    } else {
      throw pypto::ir::ValueError("Invalid acc_to_vec_mode: " + mode_str);
    }

    std::string fp_type = TileTypeStringForTemplate(codegen, fp_tile, op->args_[1]);
    std::string template_params = ", " + fp_type + ", " + mode_enum;
    if (!relu_template.empty()) {
      template_params += ", " + relu_template;
    }
    std::string dst_type = TileTypeStringForTemplate(codegen, dst, op->args_[2]);
    std::string src_type = TileTypeStringForTemplate(codegen, src, op->args_[0]);
    codegen.Emit("TMOV<" + dst_type + ", " + src_type + template_params + ">(" + args + ");");
    return "";
  }

  if (!relu_template.empty()) {
    std::string dst_type = TileTypeStringForTemplate(codegen, dst, op->args_[2]);
    std::string src_type = TileTypeStringForTemplate(codegen, src, op->args_[0]);
    std::string fp_type = TileTypeStringForTemplate(codegen, fp_tile, op->args_[1]);
    codegen.Emit("TMOV_FP<" + dst_type + ", " + src_type + ", " + fp_type + ", " +
                 relu_template + ">(" + args + ");");
  } else {
    codegen.Emit("TMOV_FP(" + args + ");");
  }

  return "";
}

// ============================================================================
// manual.set_validshape �?args = [row, col, tile]
// Emits: tile.SetValidShape(row, col);
// ============================================================================
static std::string MakeManualSetValidShapeCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.set_validshape: expected 3 args (row, col, tile), got "
                               << op->args_.size();
  std::string row = codegen.GetExprAsCode(op->args_[0]);
  std::string col = codegen.GetExprAsCode(op->args_[1]);
  std::string tile = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(tile + ".SetValidShape(" + row + ", " + col + ");");
  return "";
}

// ============================================================================
// manual.matmul �?args = [left, right, dst]
// Emits: TMATMUL(dst, left, right);
// ============================================================================
static std::string MakeManualMatmulCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.matmul: expected 3 args (left, right, dst), got "
                               << op->args_.size();
  std::string left = codegen.GetExprAsCode(op->args_[0]);
  std::string right = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TMATMUL(" + dst + ", " + left + ", " + right + ");");
  return "";
}

// manual.matmul_acc �?args = [acc, left, right, dst]
static std::string MakeManualMatmulAccCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 4) << "manual.matmul_acc: expected 4 args, got " << op->args_.size();
  std::string acc = codegen.GetExprAsCode(op->args_[0]);
  std::string left = codegen.GetExprAsCode(op->args_[1]);
  std::string right = codegen.GetExprAsCode(op->args_[2]);
  std::string dst = codegen.GetExprAsCode(op->args_[3]);
  codegen.Emit("TMATMUL_ACC(" + dst + ", " + acc + ", " + left + ", " + right + ");");
  return "";
}

// manual.cast �?args = [src, dst] + mode kwarg
static std::string MakeManualCastCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.cast: expected 2 args (src, dst), got " << op->args_.size();
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);

  // Get round mode from kwargs �?manual.cast uses a string mode
  const std::string& mode_str = op->GetKwarg<std::string>("mode");
  static const std::vector<std::string> kModeNames = {"none", "rint",  "round", "floor",
                                                       "ceil", "trunc", "odd",   "cast_rint"};
  int mode_idx = -1;
  for (int i = 0; i < static_cast<int>(kModeNames.size()); ++i) {
    if (kModeNames[i] == mode_str) {
      mode_idx = i;
      break;
    }
  }
  CHECK(mode_idx >= 0) << "manual.cast: unknown round mode '" << mode_str << "'";

  codegen.Emit("TCVT(" + dst + ", " + src + ", " +
               codegen.GetTypeConverter().ConvertCastRoundMode(mode_idx) + ");");
  return "";
}

// manual.full/expands �?args = [scalar, dst]
static std::string MakeManualExpandsCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.full/expands: expected 2 args (scalar, dst), got "
                               << op->args_.size();
  std::string scalar = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);

  // aicore does not allow implicit cast from integer (including index) to float.
  // Insert explicit (float) cast when scalar is integer/index and dst element type is float.
  auto scalar_type = ir::As<ir::ScalarType>(op->args_[0]->GetType());
  auto tile_type   = ir::As<ir::TileType>(op->args_[1]->GetType());
  if (scalar_type && tile_type) {
    bool src_is_int = (scalar_type->dtype_ == DataType::INDEX  ||
                       scalar_type->dtype_ == DataType::INT8   ||
                       scalar_type->dtype_ == DataType::INT16  ||
                       scalar_type->dtype_ == DataType::INT32  ||
                       scalar_type->dtype_ == DataType::INT64  ||
                       scalar_type->dtype_ == DataType::UINT8  ||
                       scalar_type->dtype_ == DataType::UINT16 ||
                       scalar_type->dtype_ == DataType::UINT32 ||
                       scalar_type->dtype_ == DataType::UINT64);
    bool dst_is_float = (tile_type->dtype_ == DataType::FP16  ||
                         tile_type->dtype_ == DataType::FP32  ||
                         tile_type->dtype_ == DataType::BF16);
    if (src_is_int && dst_is_float) {
      // aicore forbids direct unsigned→float cast; go via int64_t first.
      scalar = "(float)((int64_t)(" + scalar + "))";
    }
  }

  codegen.Emit("TEXPANDS(" + dst + ", " + scalar + ");");
  return "";
}

static bool NeedsNullPadSourceAliasCCE(const ir::TileTypePtr& tile_type) {
  return tile_type != nullptr && tile_type->tile_view_.has_value() &&
         tile_type->tile_view_.value().pad != ir::TilePad::null;
}

static std::pair<int64_t, int64_t> GetTileRowsCols(const ir::TileTypePtr& tile_type) {
  CHECK(tile_type != nullptr) << "manual.fillpad-like: expected TileType source";
  CHECK(tile_type->shape_.size() == 2)
      << "manual.fillpad-like: expected rank-2 tile, got " << tile_type->shape_.size();

  auto rows = ir::As<ir::ConstInt>(tile_type->shape_[0]);
  auto cols = ir::As<ir::ConstInt>(tile_type->shape_[1]);
  CHECK(rows != nullptr && cols != nullptr) << "manual.fillpad-like: expected static tile rows/cols";
  return {rows->value_, cols->value_};
}

static std::string BuildNullPadSourceAliasCCE(codegen::CCECodegen& codegen,
                                              const ir::TileTypePtr& src_tile_type,
                                              const std::string& src_name) {
  CHECK(src_tile_type != nullptr) << "manual.fillpad-like: expected TileType source";
  CHECK(src_tile_type->tile_view_.has_value()) << "manual.fillpad-like: expected source tile_view";

  auto [rows, cols] = GetTileRowsCols(src_tile_type);
  auto alias_tile_view = src_tile_type->tile_view_.value();
  alias_tile_view.pad = ir::TilePad::null;
  auto alias_tile_type = std::make_shared<ir::TileType>(
      src_tile_type->shape_, src_tile_type->dtype_, src_tile_type->memref_, alias_tile_view);

  std::string alias_tile_type_str = codegen.GetTypeConverter().ConvertTileType(alias_tile_type, rows, cols);
  static size_t fillpad_alias_counter = 0;
  std::string alias_suffix = std::to_string(fillpad_alias_counter++);
  std::string alias_type_name = "__manual_fillpad_src_alias_type_" + alias_suffix;
  std::string alias_name = "__manual_fillpad_src_alias_" + alias_suffix;

  codegen.Emit("using " + alias_type_name + " = " + alias_tile_type_str + ";");
  codegen.Emit(alias_type_name + " " + alias_name + "(" + src_name + ".GetValidRow(), " +
               src_name + ".GetValidCol());");
  codegen.Emit("TASSIGN(" + alias_name + ", " + codegen.GetTileAddress(src_name) + ");");
  return alias_name;
}

// manual.fillpad �?args = [src, dst]
static std::string MakeManualFillpadCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.fillpad: expected 2 args (src, dst), got " << op->args_.size();

  auto src_tile_type = ir::As<ir::TileType>(op->args_[0]->GetType());
  CHECK(src_tile_type != nullptr) << "manual.fillpad: expected TileType src";

  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  if (NeedsNullPadSourceAliasCCE(src_tile_type)) {
    src = BuildNullPadSourceAliasCCE(codegen, src_tile_type, src);
  }

  codegen.Emit("TFILLPAD(" + dst + ", " + src + ");");
  return "";
}

// manual.fillpad_inplace �?args = [src, dst]
static std::string MakeManualFillpadInplaceCodegenCCE(const ir::CallPtr& op,
                                                      codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2)
      << "manual.fillpad_inplace: expected 2 args (src, dst), got " << op->args_.size();

  auto src_tile_type = ir::As<ir::TileType>(op->args_[0]->GetType());
  CHECK(src_tile_type != nullptr) << "manual.fillpad_inplace: expected TileType src";

  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);

  if (NeedsNullPadSourceAliasCCE(src_tile_type)) {
    src = BuildNullPadSourceAliasCCE(codegen, src_tile_type, src);
  }

  codegen.Emit("TFILLPAD_INPLACE(" + dst + ", " + src + ");");
  return "";
}

// manual.fillpad_expand �?args = [src, dst]
static std::string MakeManualFillpadExpandCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2)
      << "manual.fillpad_expand: expected 2 args (src, dst), got " << op->args_.size();

  auto src_tile_type = ir::As<ir::TileType>(op->args_[0]->GetType());
  CHECK(src_tile_type != nullptr) << "manual.fillpad_expand: expected TileType src";

  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  if (src == dst) {
    throw pypto::ir::ValueError("manual.fillpad_expand: inplace is not supported");
  }

  if (NeedsNullPadSourceAliasCCE(src_tile_type)) {
    src = BuildNullPadSourceAliasCCE(codegen, src_tile_type, src);
  }

  codegen.Emit("TFILLPAD_EXPAND(" + dst + ", " + src + ");");
  return "";
}

// manual.reshape �?args = [src, shape, dst]
static std::string MakeManualReshapeCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.reshape: expected 3 args (src, shape, dst), got "
                               << op->args_.size();
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TRESHAPE(" + dst + ", " + src + ");");
  return "";
}

// manual.transpose �?args = [src, dst]
static std::string MakeManualTransposeCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.transpose: expected 2 args (src, dst), got " << op->args_.size();
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  // A5 CCE builtin requires the explicit tmp operand for TTRANS.
  // Reuse the source tile as the temporary buffer, matching PTO ISA demos.
  codegen.Emit("TTRANS(" + dst + ", " + src + ", " + src + ");");
  return "";
}

// manual.cmp — args = [lhs, rhs, dst] + cmp_type kwarg
static std::string GetCmpModeEnumCCE(int cmp_type) {
  switch (cmp_type) {
    case 0:
      return "CmpMode::EQ";
    case 1:
      return "CmpMode::NE";
    case 2:
      return "CmpMode::LT";
    case 3:
      return "CmpMode::LE";
    case 4:
      return "CmpMode::GT";
    case 5:
      return "CmpMode::GE";
    default:
      CHECK(false) << "Unsupported cmp_type for CCE codegen: " << cmp_type;
      return "CmpMode::EQ";
  }
}

static std::string MakeManualCmpCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.cmp: expected 3 args (lhs, rhs, dst), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  int cmp_type = op->GetKwarg<int>("cmp_type");
  codegen.Emit("TCMP(" + dst + ", " + lhs + ", " + rhs + ", " + GetCmpModeEnumCCE(cmp_type) + ");");
  return "";
}

// manual.cmps �?args = [tile, scalar, dst] + cmp_type kwarg
static std::string MakeManualCmpsCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.cmps: expected 3 args (tile, scalar, dst), got "
                               << op->args_.size();
  std::string tile = codegen.GetExprAsCode(op->args_[0]);
  std::string scalar = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  int cmp_type = op->GetKwarg<int>("cmp_type");
  codegen.Emit("TCMPS(" + dst + ", " + tile + ", " + scalar + ", " + GetCmpModeEnumCCE(cmp_type) + ");");
  return "";
}

// manual.ub_copy �?args = [src, dst] (Vec→Vec copy)
static std::string MakeManualUbCopyCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  return MakeManualMoveCodegenCCE(op, codegen_base);
}

// manual.col_expand �?args = [src, dst]
static std::string MakeManualColExpandCodegenCCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.col_expand: expected 2 args (src, dst), got " << op->args_.size();
  // TCOLEXPAND is inplace: dst and src share same buffer
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  codegen.Emit("TCOLEXPAND(" + dst + ", " + src + ");");
  return "";
}

// manual.row_expand �?args = [src, dst]
static std::string MakeManualRowExpandUnaryCodegenCCE(const ir::CallPtr& op,
                                                       codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 2) << "manual.row_expand: expected 2 args (src, dst), got " << op->args_.size();
  std::string src = codegen.GetExprAsCode(op->args_[0]);
  std::string dst = codegen.GetExprAsCode(op->args_[1]);
  codegen.Emit("TROWEXPAND(" + dst + ", " + src + ");");
  return "";
}

// ============================================================================
// Helper: Manual ternary op �?args = [a, b, c, dst]
// Emits: OP(dst, a, b, c);
// ============================================================================
static std::string MakeManualTernaryCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                               codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 4) << cce_op_name << ": expected 4 args (a, b, c, dst), got " << op->args_.size();
  std::string a   = codegen.GetExprAsCode(op->args_[0]);
  std::string b   = codegen.GetExprAsCode(op->args_[1]);
  std::string c   = codegen.GetExprAsCode(op->args_[2]);
  std::string dst = codegen.GetExprAsCode(op->args_[3]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + a + ", " + b + ", " + c + ");");
  return "";
}

// ============================================================================
// Helper: Manual quaternary op �?args = [a, b, c, d, dst]
// Emits: OP(dst, a, b, c, d);
// ============================================================================
static std::string MakeManualQuaternaryCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                  codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 5) << cce_op_name << ": expected 5 args (a, b, c, d, dst), got " << op->args_.size();
  std::string a   = codegen.GetExprAsCode(op->args_[0]);
  std::string b   = codegen.GetExprAsCode(op->args_[1]);
  std::string c   = codegen.GetExprAsCode(op->args_[2]);
  std::string d   = codegen.GetExprAsCode(op->args_[3]);
  std::string dst = codegen.GetExprAsCode(op->args_[4]);
  codegen.Emit(cce_op_name + "(" + dst + ", " + a + ", " + b + ", " + c + ", " + d + ");");
  return "";
}

// ============================================================================
// Helper: Binary + ReLU �?args = [lhs, rhs, dst]
// Semantics: dst = max(0, OP(lhs, rhs))
// Emits: OP(lhs, lhs, rhs); TRELU(dst, lhs);
// ============================================================================
static std::string MakeManualBinaryReluCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                   codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << "+relu: expected 3 args (lhs, rhs, dst), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit(cce_op_name + "(" + lhs + ", " + lhs + ", " + rhs + ");");
  codegen.Emit("TRELU(" + dst + ", " + lhs + ");");
  return "";
}

// ============================================================================
// Helper: Binary + ReLU + Cast �?args = [lhs, rhs, dst] + mode kwarg
// Semantics: dst = cast(max(0, OP(lhs, rhs)), mode)
// Emits: OP(lhs, lhs, rhs); TRELU(lhs, lhs); TCVT(dst, lhs, mode);
// ============================================================================
static std::string MakeManualBinaryReluCastCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                       codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << "+relu+cast: expected 3 args (lhs, rhs, dst), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  const std::string& mode_str = op->GetKwarg<std::string>("mode");
  static const std::vector<std::string> kModeNames = {"none", "rint", "round", "floor",
                                                       "ceil", "trunc", "odd", "cast_rint"};
  int mode_idx = -1;
  for (int i = 0; i < static_cast<int>(kModeNames.size()); ++i) {
    if (kModeNames[i] == mode_str) { mode_idx = i; break; }
  }
  CHECK(mode_idx >= 0) << cce_op_name << "+relu+cast: unknown round mode '" << mode_str << "'";
  codegen.Emit(cce_op_name + "(" + lhs + ", " + lhs + ", " + rhs + ");");
  codegen.Emit("TRELU(" + lhs + ", " + lhs + ");");
  codegen.Emit("TCVT(" + dst + ", " + lhs + ", " +
               codegen.GetTypeConverter().ConvertCastRoundMode(mode_idx) + ");");
  return "";
}

// ============================================================================
// Helper: Binary + Cast �?args = [lhs, rhs, dst] + mode kwarg
// Semantics: dst = cast(OP(lhs, rhs), mode)
// Emits: OP(lhs, lhs, rhs); TCVT(dst, lhs, mode);
// ============================================================================
static std::string MakeManualBinaryCastCodegenCCE(const std::string& cce_op_name, const ir::CallPtr& op,
                                                   codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << cce_op_name << "+cast: expected 3 args (lhs, rhs, dst), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string dst = codegen.GetExprAsCode(op->args_[2]);
  const std::string& mode_str = op->GetKwarg<std::string>("mode");
  static const std::vector<std::string> kModeNames = {"none", "rint", "round", "floor",
                                                       "ceil", "trunc", "odd", "cast_rint"};
  int mode_idx = -1;
  for (int i = 0; i < static_cast<int>(kModeNames.size()); ++i) {
    if (kModeNames[i] == mode_str) { mode_idx = i; break; }
  }
  CHECK(mode_idx >= 0) << cce_op_name << "+cast: unknown round mode '" << mode_str << "'";
  codegen.Emit(cce_op_name + "(" + lhs + ", " + lhs + ", " + rhs + ");");
  codegen.Emit("TCVT(" + dst + ", " + lhs + ", " +
               codegen.GetTypeConverter().ConvertCastRoundMode(mode_idx) + ");");
  return "";
}

// ============================================================================
// manual.mul_add_dst �?args = [lhs, rhs, out]
// Semantics: out = (lhs * rhs) + out
// Emits: TMUL(lhs, lhs, rhs); TADD(out, lhs, out);
// ============================================================================
static std::string MakeManualMulAddDstCodegenCCE(const ir::CallPtr& op,
                                                  codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.mul_add_dst: expected 3 args (lhs, rhs, out), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string out = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TMUL(" + lhs + ", " + lhs + ", " + rhs + ");");
  codegen.Emit("TADD(" + out + ", " + lhs + ", " + out + ");");
  return "";
}

// ============================================================================
// manual.fused_mul_add �?args = [lhs, rhs, out]
// Semantics: out = (lhs * out) + rhs
// Emits: TMUL(lhs, lhs, out); TADD(out, lhs, rhs);
// ============================================================================
static std::string MakeManualFusedMulAddCodegenCCE(const ir::CallPtr& op,
                                                    codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.fused_mul_add: expected 3 args (lhs, rhs, out), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string out = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TMUL(" + lhs + ", " + lhs + ", " + out + ");");
  codegen.Emit("TADD(" + out + ", " + lhs + ", " + rhs + ");");
  return "";
}

// ============================================================================
// manual.fused_mul_add_relu �?args = [lhs, rhs, out]
// Semantics: out = max(0, (lhs * out) + rhs)
// Emits: TMUL(lhs, lhs, out); TADD(lhs, lhs, rhs); TRELU(out, lhs);
// ============================================================================
static std::string MakeManualFusedMulAddReluCodegenCCE(const ir::CallPtr& op,
                                                        codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  CHECK(op->args_.size() == 3) << "manual.fused_mul_add_relu: expected 3 args (lhs, rhs, out), got " << op->args_.size();
  std::string lhs = codegen.GetExprAsCode(op->args_[0]);
  std::string rhs = codegen.GetExprAsCode(op->args_[1]);
  std::string out = codegen.GetExprAsCode(op->args_[2]);
  codegen.Emit("TMUL(" + lhs + ", " + lhs + ", " + out + ");");
  codegen.Emit("TADD(" + lhs + ", " + lhs + ", " + rhs + ");");
  codegen.Emit("TRELU(" + out + ", " + lhs + ");");
  return "";
}

// ============================================================================
// manual.gather �?args = [src, indices, out] or [src, indices, tmp, out]
// Emits: TGATHER(out, src, indices) or TGATHER(out, src, indices, tmp);
// ============================================================================
static std::string MakeManualGatherCodegenCCE(const ir::CallPtr& op,
                                               codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  if (op->args_.size() == 3) {
    std::string src     = codegen.GetExprAsCode(op->args_[0]);
    std::string indices = codegen.GetExprAsCode(op->args_[1]);
    std::string out     = codegen.GetExprAsCode(op->args_[2]);
    codegen.Emit("TGATHER(" + out + ", " + src + ", " + indices + ");");
  } else {
    CHECK(op->args_.size() == 4) << "manual.gather: expected 3 or 4 args, got " << op->args_.size();
    std::string src     = codegen.GetExprAsCode(op->args_[0]);
    std::string indices = codegen.GetExprAsCode(op->args_[1]);
    std::string tmp     = codegen.GetExprAsCode(op->args_[2]);
    std::string out     = codegen.GetExprAsCode(op->args_[3]);
    codegen.Emit("TGATHER(" + out + ", " + src + ", " + indices + ", " + tmp + ");");
  }
  return "";
}

// ============================================================================
// Op registrations �?Memory
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.load")
    .set_pipe(ir::PipeType::MTE2)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualLoadCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.store")
    .set_pipe(ir::PipeType::MTE3)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualStoreCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.store_fp")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualStoreFpCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.make_tile")
    .set_pipe(ir::PipeType::MTE2)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMakeTileCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.set_validshape")
    .set_pipe(ir::PipeType::S)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualSetValidShapeCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.move")
    .set_pipe(ir::PipeType::MTE1)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMoveCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.move_fp")
    .set_pipe(ir::PipeType::FIX)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMoveFpCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.insert")
    .set_pipe(ir::PipeType::MTE1)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualInsertCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.ub_copy")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUbCopyCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.full")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualExpandsCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.fillpad")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualFillpadCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.fillpad_inplace")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualFillpadInplaceCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.fillpad_expand")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualFillpadExpandCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Tile x Tile binary
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.add")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TADD", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sub")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TSUB", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mul")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TMUL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.div")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TDIV", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.rem")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TREM", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.maximum")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TMAX", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.minimum")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TMIN", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.and")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TAND", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.or")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TOR", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.shl")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TSHL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.shr")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TSHR", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.add_relu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryReluCodegenCCE("TADD", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sub_relu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryReluCodegenCCE("TSUB", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.add_relu_cast")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryReluCastCodegenCCE("TADD", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sub_relu_cast")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryReluCastCodegenCCE("TSUB", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mul_cast")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCastCodegenCCE("TMUL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mul_add_dst")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMulAddDstCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.fused_mul_add")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualFusedMulAddCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.fused_mul_add_relu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualFusedMulAddReluCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Tile x Scalar binary
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.adds")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TADDS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.subs")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TSUBS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.muls")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TMULS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.divs")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TDIVS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.rems")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TREMS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.ands")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TANDS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.ors")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TORS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.shls")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TSHLS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.shrs")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TSHRS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.maxs")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TMAXS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mins")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TMINS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.lrelu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualScalarCodegenCCE("TLRELU", op, codegen);
    });

// ============================================================================
// Op registrations �?Unary
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.neg")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TNEG", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.exp")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TEXP", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sqrt")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TSQRT", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.rsqrt")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TRSQRT", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.recip")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TRECIP", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.log")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TLOG", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.abs")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TABS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.relu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TRELU", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.not")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualUnaryCodegenCCE("TNOT", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.cast")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualCastCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Comparison
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.cmp")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualCmpCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.cmps")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualCmpsCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Scalar broadcast
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.expands")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualExpandsCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Reductions (tile, tmp, out)
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_sum")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowReductionCodegenCCE("TROWSUM", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_max")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowReductionCodegenCCE("TROWMAX", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_min")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowReductionCodegenCCE("TROWMIN", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_max")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualColMaxCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_sum")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualColSumCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Broadcast expansion
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_expand")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandUnaryCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_expand_add")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TROWEXPANDADD", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_expand_sub")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TROWEXPANDSUB", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_expand_mul")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TROWEXPANDMUL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.row_expand_div")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TROWEXPANDDIV", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_expand")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualColExpandCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_expand_mul")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TCOLEXPANDMUL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_expand_div")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TCOLEXPANDDIV", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.col_expand_sub")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualRowExpandCodegenCCE("TCOLEXPANDSUB", op, codegen);
    });

// ============================================================================
// Op registrations �?Matrix multiplication
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.matmul")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMatmulCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.matmul_acc")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMatmulAccCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.matmul_bias")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualQuaternaryCodegenCCE("TMATMUL_BIAS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.gemv")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TGEMV", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.gemv_acc")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TGEMV_ACC", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.gemv_bias")
    .set_pipe(ir::PipeType::M)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TGEMV_BIAS", op, codegen);
    });

// ============================================================================
// Op registrations �?Layout operations
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.reshape")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualReshapeCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.transpose")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTransposeCodegenCCE(op, codegen);
    });

// ============================================================================
// Op registrations �?Ternary / multi-input
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.xor")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TXOR", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.xors")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TXORS", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.prelu")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TPRELU", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.addc")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TADDC", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.subc")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TSUBC", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.addsc")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TADDSC", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.subsc")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TSUBSC", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sel")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualQuaternaryCodegenCCE("TSEL", op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sels")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualTernaryCodegenCCE("TSELS", op, codegen);
    });

// ============================================================================
// Op registrations �?Gather / scatter
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.gather")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualGatherCodegenCCE(op, codegen);
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.gatherb")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualBinaryCodegenCCE("TGATHERB", op, codegen);
    });

// ============================================================================
// Op registrations �?Struct array (C++ struct + array for pl.struct lists)
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "struct.declare")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      std::string arr_name = op->GetKwarg<std::string>("array");
      int size = op->GetKwarg<int>("size");
      std::string fields_csv = op->GetKwarg<std::string>("fields");

      // Deduplicate: same fields �?same struct type
      std::string type_name = codegen.GetOrCreateStructType(fields_csv, arr_name);

      // Emit variable declaration only (type definition already emitted)
      if (size == 1) {
        codegen.Emit(type_name + " " + arr_name + " = {};");
      } else {
        codegen.Emit(type_name + " " + arr_name + "[" + std::to_string(size) + "] = {};");
      }
      return std::string("");
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "struct.get")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      CHECK(op->args_.size() == 1) << "struct.get requires 1 arg (index)";
      std::string arr_name = op->GetKwarg<std::string>("array");
      std::string field = op->GetKwarg<std::string>("field");
      std::string ref = op->GetKwarg<std::string>("ref");
      // If a C++ reference exists, use it: "ref.field"
      if (!ref.empty()) {
        return ref + "." + field;
      }
      // For constant-0 index (single struct), emit "name.field" instead of "name[0].field"
      auto cint = ir::As<ir::ConstInt>(op->args_[0]);
      if (cint && cint->value_ == 0) {
        return arr_name + "." + field;
      }
      std::string idx = codegen.GetExprAsCode(op->args_[0]);
      return arr_name + "[" + idx + "]." + field;
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "struct.set")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      CHECK(op->args_.size() == 2) << "struct.set requires 2 args (index, value)";
      std::string val = codegen.GetExprAsCode(op->args_[1]);
      std::string arr_name = op->GetKwarg<std::string>("array");
      std::string field = op->GetKwarg<std::string>("field");
      std::string ref = op->GetKwarg<std::string>("ref");
      // If a C++ reference exists, use it: "ref.field = val;"
      if (!ref.empty()) {
        codegen.Emit(ref + "." + field + " = " + val + ";");
        return std::string("");
      }
      // For constant-0 index (single struct), emit "name.field = val;"
      auto cint = ir::As<ir::ConstInt>(op->args_[0]);
      if (cint && cint->value_ == 0) {
        codegen.Emit(arr_name + "." + field + " = " + val + ";");
      } else {
        std::string idx = codegen.GetExprAsCode(op->args_[0]);
        codegen.Emit(arr_name + "[" + idx + "]." + field + " = " + val + ";");
      }
      return std::string("");
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "struct.ref")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      CHECK(op->args_.size() == 1) << "struct.ref requires 1 arg (index)";
      std::string idx = codegen.GetExprAsCode(op->args_[0]);
      std::string arr_name = op->GetKwarg<std::string>("array");
      std::string var_name = op->GetKwarg<std::string>("var");
      codegen.Emit("auto& " + var_name + " = " + arr_name + "[" + idx + "];");
      return std::string("");
    });

// ============================================================================
// Op registrations �?Sorting
// ============================================================================

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.sort32")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      CHECK(op->args_.size() == 3 || op->args_.size() == 4)
          << "manual.sort32: expected 3 or 4 args (src, idx, dst[, tmp]), got "
          << op->args_.size();
      
      std::string src = codegen.GetExprAsCode(op->args_[0]);
      std::string idx = codegen.GetExprAsCode(op->args_[1]);
      std::string dst = codegen.GetExprAsCode(op->args_[2]);
      
      if (op->args_.size() == 4) {
        std::string tmp = codegen.GetExprAsCode(op->args_[3]);
        codegen.Emit("TSORT32(" + dst + ", " + src + ", " + idx + ", " + tmp + ");");
      } else {
        codegen.Emit("TSORT32(" + dst + ", " + src + ", " + idx + ");");
      }
      return "";
    });

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mrgsort")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
      auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
      CHECK(op->args_.size() == 2)
          << "manual.mrgsort: expected 2 args (src, dst), got "
          << op->args_.size();
      
      std::string src = codegen.GetExprAsCode(op->args_[0]);
      std::string dst = codegen.GetExprAsCode(op->args_[1]);
      int block_len = op->GetKwarg<int>("block_len");
      
      codegen.Emit("TMRGSORT(" + dst + ", " + src + ", " + std::to_string(block_len) + ");");
      return "";
    });

// mrgsort2 (format2): Multi-list merge sort for CCE backend
static std::string MakeManualMrgsort2CCE(const ir::CallPtr& op, codegen::CodegenBase& codegen_base) {
  auto& codegen = dynamic_cast<codegen::CCECodegen&>(codegen_base);
  size_t num_args = op->args_.size();
  CHECK(num_args >= 4 && num_args <= 6)
      << "manual.mrgsort2: expected 4-6 args, got " << num_args;

  bool exhausted = op->GetKwarg<bool>("exhausted");
  std::string exhausted_str = exhausted ? "true" : "false";

  std::string src0 = codegen.GetExprAsCode(op->args_[0]);
  std::string dst  = codegen.GetExprAsCode(op->args_[1]);
  std::string tmp  = codegen.GetExprAsCode(op->args_[2]);
  std::string src1 = codegen.GetExprAsCode(op->args_[3]);

  // TMRGSORT requires exhausted as a non-deducible bool template parameter.
  // Use TMRGSORT_IMPL with decltype() to avoid spelling out all tile types explicitly.
  auto emit_tmrgsort = [&](const std::string& srcs_decl, const std::string& srcs_args) {
    std::ostringstream oss;
    oss << "MrgSortExecutedNumList executedNumList;";
    codegen.Emit(oss.str());
    oss.str("");
    oss << "TMRGSORT_IMPL<decltype(" << dst << "), decltype(" << tmp << "), "
        << srcs_decl << ", " << exhausted_str << ">("
        << dst << ", executedNumList, " << tmp << ", " << srcs_args << ");";
    codegen.Emit(oss.str());
  };

  if (num_args == 4) {
    emit_tmrgsort("decltype(" + src0 + "), decltype(" + src1 + ")",
                  src0 + ", " + src1);
  } else if (num_args == 5) {
    std::string src2 = codegen.GetExprAsCode(op->args_[4]);
    emit_tmrgsort("decltype(" + src0 + "), decltype(" + src1 + "), decltype(" + src2 + ")",
                  src0 + ", " + src1 + ", " + src2);
  } else {
    std::string src2 = codegen.GetExprAsCode(op->args_[4]);
    std::string src3 = codegen.GetExprAsCode(op->args_[5]);
    emit_tmrgsort("decltype(" + src0 + "), decltype(" + src1 + "), decltype(" + src2 + "), decltype(" + src3 + ")",
                  src0 + ", " + src1 + ", " + src2 + ", " + src3);
  }
  return "";
}

REGISTER_BACKEND_OP(Backend910B_CCE, "manual.mrgsort2")
    .set_pipe(ir::PipeType::V)
    .f_codegen([](const ir::CallPtr& op, codegen::CodegenBase& codegen) {
      return MakeManualMrgsort2CCE(op, codegen);
    });

}  // namespace backend
}  // namespace pypto

