import enum
from typing import Iterator, overload, Union, List, Dict


class DataType(enum.Enum):
    ...


DT_INT4 = ...
DT_INT8 = ...
DT_INT16 = ...
DT_INT32 = ...
DT_INT64 = ...
DT_FP8 = ...
DT_FP16 = ...
DT_FP32 = ...
DT_BF16 = ...
DT_HF4 = ...
DT_HF8 = ...
DT_UINT8 = ...
DT_UINT16 = ...
DT_UINT32 = ...
DT_UINT64 = ...
DT_BOOL = ...
DT_DOUBLE = ...


class NodeType(enum.Enum):
    LOCAL = ...
    INCAST = ...
    OUTCAST = ...


class TileOpFormat(enum.Enum):
    TILEOP_ND = ...
    TILEOP_NZ = ...


class CachePolicy(enum.Enum):
    PREFETCH = ...
    NONE_CACHEABLE = ...


class ReduceMode(enum.Enum):
    ATOMIC_ADD = ...


class MemoryType(enum.Enum):
    MEM_UB = ...
    MEM_L1 = ...
    MEM_L0A = ...
    MEM_L0B = ...
    MEM_L0C = ...
    MEM_DEVICE_DDR = ...


class FunctionType(enum.Enum):
    STATIC = ...
    DYNAMIC = ...
    DYNAMIC_LOOP = ...


class GraphType:
    TENSOR_GRAPH = ...


class CastMode(enum.Enum):
    CAST_NONE = ...
    CAST_RINT = ...
    CAST_ROUND = ...
    CAST_FLOOR = ...
    CAST_CEIL = ...
    CAST_TRUNC = ...
    CAST_ODD = ...


class LogBaseType(enum.Enum):
    LOG_e = ...
    LOG_2 = ...
    LOG_10 = ...


class OpType(enum.Enum):
    EQ = ...
    NE = ...
    LT = ...
    LE = ...
    GT = ...
    GE = ...


class OutType(enum.Enum):
    BOOL = ...
    BIT = ...


class Element:

    def __init__(self, dtype: DataType, data: Union[int, float]): ...

    def _get_signed_data(self) -> int: ...

    def _get_float_data(self) -> float: ...

    def _get_data_type(self) -> DataType: ...


class SymbolicScalar:

    @overload
    def __init__(self): ...

    @overload
    def __init__(self, name: str): ...

    @overload
    def __init__(self, value: int): ...

    @overload
    def __init__(self, name: str, val: int): ...

    def IsImmediate(self) -> bool: ...
    def IsSymbol(self) -> bool: ...
    def IsExpression(self) -> bool: ...
    def ConcreteValid(self) -> bool: ...
    def Concrete(self) -> int: ...
    def AsIntermediateVariable(self) -> None: ...
    def Dump(self) -> str: ...

    def Eq(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Ne(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Lt(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Le(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Gt(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Ge(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def RAdd(self, other: int) -> SymbolicScalar: ...
    def RSub(self, other: int) -> SymbolicScalar: ...
    def RMul(self, other: int) -> SymbolicScalar: ...
    def RDiv(self, other: int) -> SymbolicScalar: ...
    def RMod(self, other: int) -> SymbolicScalar: ...
    def Add(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Sub(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Mul(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Div(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Mod(self, other: Union[SymbolicScalar, int]) -> SymbolicScalar: ...
    def Pos(self) -> SymbolicScalar: ...
    def Neg(self) -> SymbolicScalar: ...
    def Not(self) -> SymbolicScalar: ...


class Tensor:

    @overload
    def __init__(self): ...

    @overload
    def __init__(self, dtype: DataType, shape: List[int],
                 name: str = "", format: TileOpFormat = TileOpFormat.TILEOP_ND): ...

    @overload
    def __init__(self, dtype: DataType, shape: List[SymbolicScalar],
                 name: str = "", format: TileOpFormat = TileOpFormat.TILEOP_ND): ...

    def GetDataType(self) -> DataType: ...

    def GetShape(self) -> List[int]: ...

    def GetShapeAt(self, index: int) -> int: ...

    def Move(self, other: Tensor) -> Tensor: ...

    def SetCachePolicy(self, policy: CachePolicy, value: bool): ...
    def GetCachePolicy(self, policy: CachePolicy) -> bool: ...
    def SetName(self, name: str): ...
    def GetName(self) -> str: ...
    def Id(self) -> int: ...
    def Dim(self) -> int: ...
    def reshape(self, *shape: List[int]) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def view(self, shape: List[int], offsets: List[int]) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def sigmoid(self) -> Tensor: ...
    def softmax(self, dim: int) -> Tensor: ...

def GetInputShape(a: Tensor, axis: int) -> SymbolicScalar: ...


def GetInputData(
    a: Tensor, offsets: List[SymbolicScalar]) -> SymbolicScalar: ...


def GetTensorData(
    a: Tensor, offset: List[SymbolicScalar]) -> SymbolicScalar: ...


def SetTensorData(value: SymbolicScalar,
                  offset: List[SymbolicScalar], dst: Tensor): ...

def MarkInputDynamic(a: Tensor, axis: int): ...

class RecordIfBranch:

    def __init__(self, cond: SymbolicScalar,
                 file: str = "", line: int = 0): ...

    def __bool__(self) -> bool: ...


class LoopRange:

    def __init__(self, start: SymbolicScalar, stop: SymbolicScalar,
                 step: Union[SymbolicScalar, int]): ...

    def Dump(self) -> str: ...
    def Begin(self) -> SymbolicScalar: ...
    def End(self) -> SymbolicScalar: ...
    def Step(self) -> SymbolicScalar: ...


def IsLoopBegin(symbol: SymbolicScalar, begin: SymbolicScalar) -> SymbolicScalar: ...
def IsLoopEnd(symbol: SymbolicScalar, end: SymbolicScalar) -> SymbolicScalar: ...


class RecordFunc:

    @overload
    def __init__(self, name: str): ...

    @overload
    def __init__(self, name: str, args: List[Tensor]): ...

    @overload
    def __init__(self, name: str, inputs: List[Tensor] = [], outputs: List[Tensor] = [],
                 inplaces: List[tuple[Tensor, Tensor]] = []): ...


class RecordLoopFunc:

    def __init__(self, name: str, func_type: FunctionType, iter_name: str, loop_range: LoopRange,
                 unroll_List: set[int] = set(), submit_before_loop: bool = False): ...

    def __iter__(self) -> Iterator[SymbolicScalar]: ...


def BeginFunction(name: str, graph_type: GraphType,
                  func_type: FunctionType, *args) -> RecordFunc: ...


def EndFunction(name: str, generate_call: bool = True): ...


def SetVecTile(*shapes: int): ...
def GetVecTile() -> List[int]: ...
def SetCubeTile(m: List[int], k: List[int],
                n: List[int], set_l1_tile: bool = False): ...
def GetCubeTile() -> List[Union[List, bool]]: ...
def SetMatrixSize(size: List[int]): ...


def SetBuildStatic(static: bool): ...
def SetSemanticLabel(label: str): ...

def SetPrintOptions(edge_items: int, precision: int, threshold: int, linewidth: int): ...
def GetPrintOptions(): ...
def SetPassOption(key: str, value: Union[str, int, List[int], dict[int, int]]): ...
def GetPassOption(key: str): ...
def SetHostOption(key: str, value: Union[str, int, List[int], dict[int, int]]): ...
def GetHostOption(key: str): ...
def SetCodeGenOption(key: str, value: Union[str, int, List[int], Dict[int, int]]): ...
def GetCodeGenOption(key: str):
def SetRuntimeOption(key: str, value: Union[str, int, List[int], Dict[int, int]]): ...
def GetRuntimeOption(key: str):

@overload
def SetOption(key: str, value: bool): ...
@overload
def SetOption(key: str, value: str): ...
@overload
def SetOption(key: str, value: int): ...
@overload
def SetOption(key: str, value: List[int]): ...
@overload
def SetOption(key: str, value: Dict[int, int]): ...

def GetOption(key: str) -> Union[bool, str, int, List[int], Dict[int, int]]: ...

def SetPrintOptions(edge_items: int, precision: int, threshold: int, linewidth: int): ...


def BytesOf(t: DataType) -> int: ...
def Reset(): ...
def Dump() -> str: ...

# operations


def add(a: Tensor, b: Tensor) -> Tensor: ...
def sub(a: Tensor, b: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def div(a: Tensor, b: Tensor) -> Tensor: ...


@overload
def view(a: Tensor, shapes: List[int],
         offsets: List[SymbolicScalar]) -> Tensor: ...


@overload
def view(a: Tensor, shapes: List[int], valid_shape: List[SymbolicScalar],
         offsets: List[SymbolicScalar]) -> Tensor: ...


def exp(a: Tensor) -> Tensor: ...
def transpose(a: Tensor, axis: List[int]) -> Tensor: ...
def abs(a: Tensor) -> Tensor: ...
def reciprocal(a: Tensor) -> Tensor: ...
def rsqrt(a: Tensor) -> Tensor: ...
def sqrt(a: Tensor) -> Tensor: ...
def neg(a: Tensor) -> Tensor: ...
def log(a: Tensor, base: LogBaseType) -> Tensor: ...
def cast(a: Tensor, dtype: DataType, mode: CastMode) -> Tensor: ...
def add_s(a: Tensor, b: Element) -> Tensor: ...
def sub_s(a: Tensor, b: Element) -> Tensor: ...
def mul_s(a: Tensor, b: Element) -> Tensor: ...
def div_s(a: Tensor, b: Element) -> Tensor: ...
def row_max_single(a: Tensor, axis: int = -1) -> Tensor: ...
def row_sum_single(a: Tensor, axis: int = -1) -> Tensor: ...
def compact(a: Tensor) -> Tensor: ...
def indexput(src: Tensor, indices: List[Tensor], values: Tensor) -> Tensor: ...


def scatter_(self: Tensor, indices: Tensor, src: Element,
             axis: int = -1, reduce: str = "") -> Tensor: ...


def scatter(self: Tensor, indices: Tensor, src: Element,
            axis: int = -1, reduce: str = "") -> Tensor: ...
def gather_element(params: Tensor, indices: Tensor,
                   axis: int = -1) -> Tensor: ...


def gate(a: Tensor, b: Tensor, mask: Tensor) -> Tensor: ...
def duplicate(a: Tensor) -> Tensor: ...


def vector_duplicate(
    elem: Element, shape: List[int], valid_shape: Union[List[int], List[SymbolicScalar]] = []) -> Tensor: ...
def reshape(a: Tensor, shape: List[int], valid_shape: Union[List[int], List[SymbolicScalar]] = []) -> Tensor: ...


def reduce(aggregation: List[Tensor], reduce_mode: ReduceMode) -> Tensor: ...
def maximum(a: Tensor, b: Tensor) -> Tensor: ...
def unsqueeze(a: Tensor, axis: int) -> Tensor: ...
def tensor_index(a: Tensor, indices: Tensor) -> Tensor: ...


def scatter_update(self: Tensor, indices: Tensor, src: Tensor, axis: int = -1,
                   cacheMode: str = "PA_BNSD", chunkSize: int = 1) -> Tensor: ...
def expand(a: Tensor, shape: List[int], valid_shape: Union[List[int], List[SymbolicScalar]] = [
]) -> Tensor: ...


def sin(a: Tensor) -> Tensor: ...
def cos(a: Tensor) -> Tensor: ...
def new_compact(a: Tensor) -> Tensor: ...
def logic_not(a: Tensor) -> Tensor: ...


@overload
def where(a: Tensor, b: Tensor, c: Tensor) -> Tensor: ...
@overload
def where(a: Tensor, b: Tensor, c: Element) -> Tensor: ...
@overload
def where(a: Tensor, b: Element, c: Tensor) -> Tensor: ...
@overload
def where(a: Tensor, b: Element, c: Element) -> Tensor: ...


def assign(a: Tensor) -> Tensor: ...


@overload
def rms_norm(a: Tensor) -> Tensor: ...
@overload
def rms_norm(a: Tensor, gamma: Tensor, epsilon: float = 1e-05) -> Tensor: ...


def concat(a: List[Tensor], axis: int) -> Tensor: ...
def pad(a: Tensor, new_shape: Union[List[int], List[SymbolicScalar]]) -> Tensor: ...


def topk(a: Tensor, k: int, axis: int = -1,
         islargest: bool = True) -> Tensor: ...


def matmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False,
           b_trans: bool = False, c_matrix_nz: bool = False) -> Tensor: ...
def batch_matmul(dtype: DataType, a: Tensor, b: Tensor, a_trans: bool = False,
                 b_trans: bool = False, c_matrix_nz: bool = False) -> Tensor: ...


def sort(a: Tensor, axis: int = -1, islargest: bool = True) -> Tensor: ...
def softmax(a: Tensor, axis: int = -1) -> Tensor: ...
def sigmoid(a: Tensor) -> Tensor: ...


def quantize(a: Tensor, scale: Tensor, zero_point: Tensor,
             dtype: DataType) -> Tensor: ...


def scalar_divs(a: Tensor, b: Element,
                reverse_operand: bool = False) -> Tensor: ...


def scalar_adds(a: Tensor, b: Element,
                reverse_operand: bool = False) -> Tensor: ...


def scalar_maxs(a: Tensor, b: Element,
                reverse_operand: bool = False) -> Tensor: ...


def scalar_subs(a: Tensor, b: Element,
                reverse_operand: bool = False) -> Tensor: ...
def scalar_muls(a: Tensor, b: Element,
                reverse_operand: bool = False) -> Tensor: ...


def scalar_sub(a: Tensor, b: Tensor) -> Tensor: ...
def scalar_div(a: Tensor, b: Tensor) -> Tensor: ...


@overload
def assemble(a: List[Tensor], axis: int) -> Tensor: ...


@overload
def assemble(a: Tensor, offset: List[SymbolicScalar], dst: Tensor) -> None: ...


def maxs(a: Tensor, b: Element) -> Tensor: ...
