from ..language import operations as l


def mock():
    import triton.language as tl
    mocks = (
        l.abs,
        l.advance,
        l.arange,
        l.assume,
        l.broadcast,
        l.broadcast_to,
        l.cast,
        l.cat,
        l.cdiv,
        l.clamp,
        l.cos,
        l.cumsum,
        l.debug_barrier,
        l.div_rn,
        l.dot,
        l.exp,
        l.exp2,
        l.expand_dims,
        l.fdiv,
        l.fma,
        l.full,
        l.inline_asm_elementwise,
        l.load,
        l.log,
        l.make_block_ptr,
        l.max,
        l.max_constancy,
        l.max_contiguous,
        l.maximum,
        l.min,
        l.minimum,
        l.multiple_of,
        l.num_programs,
        l.permute,
        l.program_id,
        l.range,
        l.ravel,
        l.reshape,
        l.rsqrt,
        l.sigmoid,
        l.sin,
        l.softmax,
        l.sqrt,
        l.sqrt_rn,
        l.static_assert,
        l.static_print,
        l.static_range,
        l.store,
        l.sum,
        l.trans,
        l.view,
        l.where,
        l.zeros,
        l.zeros_like,
    )
    for m in mocks:
        setattr(tl, m.__name__, m)
